<?php

namespace App\Models;

use App\Contracts\Documentable;
use Database\Factories\DocumentationChatFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;

/**
 * The Documentation Assistant ("Assiste IA") conversation for one user about
 * one target (a DocumentationPage) — one ongoing chat per (user, target):
 * reopening the panel resumes the same thread instead of starting a new one
 * (see the unique index in its migration). `target` stays a morph because it
 * once also pointed at an `Integration`, the second kind of documentation this
 * app no longer has; every row is a page today.
 */
class DocumentationChat extends Model
{
    /** @use HasFactory<DocumentationChatFactory> */
    use HasFactory;

    protected $fillable = [
        'user_id',
        'target_type',
        'target_id',
        'notebook_id',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /** @return MorphTo<Documentable, $this> */
    public function target(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * The caderno the conversation is scoped to — what owns the context
     * documents the assistant reads, and what every 404 guard on this chat
     * compares against. It was a `solution_id` until the container swap, kept
     * in sync on every request precisely because a page could be re-filed
     * under another owner while a chat about it was open; the notebook is now
     * simply the page's own container, so it can be read off the page.
     */
    public function notebook(): BelongsTo
    {
        return $this->belongsTo(Notebook::class);
    }

    public function messages(): HasMany
    {
        return $this->hasMany(DocumentationChatMessage::class)->orderBy('id');
    }

    /**
     * How long after the user's last message the chat is still considered to
     * be legitimately "generating" before the reply is treated as stalled —
     * same reasoning as FlowspecChat::REPLY_STALL_SECONDS: sized just past the
     * job timeout (GenerateDocumentationChatReply) and the client poll
     * ceiling (docs-chat.js), so a worker hard-killed mid-job doesn't leave
     * the composer locked out forever. The correctness net for a job the
     * queue resurrects after this window is
     * GenerateDocumentationChatReply::isSuperseded().
     */
    public const REPLY_STALL_SECONDS = 660;

    /**
     * The assistant's reply is generated by a job: the chat is "generating…"
     * while the last message is from the user — even a failure becomes an
     * assistant message (the job's failed()).
     */
    public function isAwaitingReply(): bool
    {
        // reorder(): messages() already orders by id asc, which would win over latest().
        return $this->awaitsReplyFor(
            $this->messages()->reorder('id', 'desc')->first(['role', 'created_at'])
        );
    }

    /**
     * A chat awaits a reply when its last message is the user's AND that
     * message is recent enough to still be inside the generation window
     * (REPLY_STALL_SECONDS). Parameterized so ChatThread can derive the same
     * "awaiting" state from a collection it already fetched, without the
     * extra query isAwaitingReply() issues.
     */
    public function awaitsReplyFor(?DocumentationChatMessage $last): bool
    {
        return $last?->role === 'user'
            && $last->created_at !== null
            && $last->created_at->greaterThan(now()->subSeconds(self::REPLY_STALL_SECONDS));
    }
}
