<?php

namespace App\Models;

use Database\Factories\FlowspecChatFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A flowSpec generator (F8) conversation: a thread of user prompts and the
 * assistant's generated flowSpec replies.
 */
class FlowspecChat extends Model
{
    /** @use HasFactory<FlowspecChatFactory> */
    use HasFactory;

    protected $fillable = [
        'user_id',
        'title',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function messages(): HasMany
    {
        return $this->hasMany(FlowspecMessage::class)->orderBy('id');
    }

    /**
     * How long after the user's last message the chat is still considered to
     * be legitimately "generating" before the reply is treated as stalled.
     * Sized just past the job timeout (GenerateFlowspecReply::$timeout, 600s)
     * and the client poll ceiling (flowspec-chat.js MAX_POLL_ATTEMPTS, ~600s):
     * a worker hard-killed (OOM/SIGKILL/deploy restart) before it either
     * finishes handle() or fires failed() never creates the assistant reply,
     * so without this bound the chat's last message stays role='user' forever
     * and the composer is locked out of that chat indefinitely. Past this
     * window the generation is treated as dead and the user can send again.
     *
     * This window is a UX timer only — it decides when to reopen the composer,
     * not whether a late/duplicate reply is safe. The correctness net for a job
     * the queue resurrects after retry_after (900s > this window), or for a
     * message that slipped past the composer during the reopen, is
     * GenerateFlowspecReply::isSuperseded(): a job whose turn already has a
     * later message writes no reply. That guard is what keeps this window from
     * needing to exceed retry_after.
     */
    public const REPLY_STALL_SECONDS = 660;

    /**
     * The assistant's reply is generated by a job (GenerateFlowspecReply): the
     * chat is "generating…" while the last message is from the user — even a
     * failure becomes an assistant message (failed()). See awaitsReplyFor() for
     * the stall bound that keeps a killed job from locking the composer forever.
     */
    public function isAwaitingReply(): bool
    {
        // reorder(): messages() already orders by id asc, which would win over latest().
        return $this->awaitsReplyFor(
            $this->messages()->reorder('id', 'desc')->first(['role', 'created_at'])
        );
    }

    /**
     * A chat awaits a reply when its last message is the user's AND that
     * message is recent enough to still be inside the generation window
     * (REPLY_STALL_SECONDS). Kept parameterized so Thread can derive the same
     * "awaiting" state from a collection it already fetched, without the extra
     * query isAwaitingReply() issues.
     */
    public function awaitsReplyFor(?FlowspecMessage $last): bool
    {
        return $last?->role === 'user'
            && $last->created_at !== null
            && $last->created_at->greaterThan(now()->subSeconds(self::REPLY_STALL_SECONDS));
    }
}
