<?php

namespace App\Models;

use Database\Factories\FlowspecChatFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A flowSpec generator (F8) conversation. Optionally linked to the
 * Integration that will receive the generated pipeline
 * (`integrations.generated_flowspec`).
 */
class FlowspecChat extends Model
{
    /** @use HasFactory<FlowspecChatFactory> */
    use HasFactory;

    protected $fillable = [
        'user_id',
        'integration_id',
        'title',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function integration(): BelongsTo
    {
        return $this->belongsTo(Integration::class);
    }

    public function messages(): HasMany
    {
        return $this->hasMany(FlowspecMessage::class)->orderBy('id');
    }

    /**
     * The assistant's reply is generated by a job (GenerateFlowspecReply): the
     * chat is "generating…" while the last message is from the user — even a
     * failure becomes an assistant message (failed()), so this always resolves.
     */
    public function isAwaitingReply(): bool
    {
        // reorder(): messages() already orders by id asc, which would win over latest().
        return $this->messages()->reorder('id', 'desc')->value('role') === 'user';
    }
}
