<?php

namespace App\Models;

use Database\Factories\SubmissionChatFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * The adaptive interview for one submission, per user — one ongoing chat per
 * (user, submission), enforced by the unique index in its migration:
 * reopening the panel resumes the same thread instead of starting a new one.
 */
class SubmissionChat extends Model
{
    /** @use HasFactory<SubmissionChatFactory> */
    use HasFactory;

    /**
     * How long after the user's last message the chat is still legitimately
     * "generating" before the reply counts as stalled — same reasoning and
     * same value as DocumentationChat::REPLY_STALL_SECONDS: sized just past
     * the job timeout and the client's poll ceiling, so a worker hard-killed
     * mid-job (a `composer dev` restart is the everyday case) doesn't lock the
     * composer out forever. The correctness net for a job the queue
     * resurrects after this window is the reply job's isSuperseded().
     */
    public const REPLY_STALL_SECONDS = 660;

    protected $fillable = [
        'user_id',
        'submission_id',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function submission(): BelongsTo
    {
        return $this->belongsTo(Submission::class);
    }

    public function messages(): HasMany
    {
        return $this->hasMany(SubmissionMessage::class)->orderBy('id');
    }

    /**
     * The assistant's reply is generated by a job: the chat is "generating…"
     * while the last message is the user's — even a failure becomes an
     * assistant message (the job's failed()).
     */
    public function isAwaitingReply(): bool
    {
        // reorder(): messages() already orders by id asc, which would win over latest().
        return $this->awaitsReplyFor(
            $this->messages()->reorder('id', 'desc')->first(['role', 'created_at'])
        );
    }

    /**
     * Parameterized so the thread component can derive the same "awaiting"
     * state from a collection it already fetched, without the extra query
     * isAwaitingReply() issues.
     */
    public function awaitsReplyFor(?SubmissionMessage $last): bool
    {
        return $last?->role === 'user'
            && $last->created_at !== null
            && $last->created_at->greaterThan(now()->subSeconds(self::REPLY_STALL_SECONDS));
    }
}
